### ISSUE TITLE
Philosopher anpassen

### ISSUE THREAD

**Issue by darenegade** [FabianHoltkoetter/VerteilteSystemePraktikum#11]
- Beim letzten Tisch weiter essen
- Melden von Fehlern am Manager

**Comment by FabianWilms** [comment]
wie soll ich denn melden welcher tisch nicht mehr verfügbar ist? an die ID des tisches komme ich als philosoph nicht ran wenn dieser weg ist.

**Comment by darenegade** [comment]
Ich bin mir sicher, dass du für dieses Problem eine effiziente und saubere Lösung findest 😉

**Comment by FabianWilms** [comment]
Defekte/Fehlende Tische werden sowieso schon im Manager in `getRandom/NextTablePart` gemeldet. Das beim Philosophen nochmal zu machen erscheint mir weniger sinnvoll.

**Comment by darenegade** [comment]
Wie oben geschrieben, sollen die Philosophen am letzten Tisch weiter essen. D.h. `getRandom/NextTablePart`wird nur beim starten eines Philosophen bzw. Tisches aufgerufen. Danach nicht mehr.

**Comment by FabianWilms** [comment]
Das ist schon klar. Aber da steht auch, dass Fehler an den Manager gemeldet werden sollen. Das würde ich sein lassen.

**Comment by darenegade** [comment]
Warum?
Damit der Manager entlastet wird, soll beim letzten Tisch weitergegessen werden. Und dann bekommt der Manager nicht mehr mit, wenn ein Tisch tot ist. (Erst wenn ein Tisch oder Phil gestartet wird) Und darum ist es notwendig, dass der Phil einen toten Tisch meldet.

**Comment by FabianWilms** [comment]
Er bekommt es dadurch mit, dass wahlweise ein anderer Table das feststellt, oder dadurch dass der Philosoph sobald er einen Fehlerhaften erreicht sich einen neuen holt.

**Comment by darenegade** [comment]
Und warum sagst du das nicht gleich so? 😉

**Comment by darenegade** [comment]
Also soll der Manager bei randomTable einmal alle checken? Kannst du gerne so umsetzen

**Comment by FabianWilms** [comment]
Weil wir vorher aneinander vorbei geredet haben und ich das Problem falsch verstanden hatte weil ich es nicht gesehen hatte :D Also wie immer :P
Würde ich nicht unbedingt machen. Dadurch, dass es ja immer zufällig ist, wird er schon die defekten erwischen.

**Comment by darenegade** [comment]
Nein, also darauf hoffen, dass er mal den falschen erwischt, find ich nicht so geil

**Comment by darenegade** [comment]
Bei 100+ Tischen kann das dann sehr sehr sehr lange dauern

**Comment by darenegade** [comment]
Und die Philosophen stoßen aber öfter an den defekten und nichts passiert

**Comment by FabianWilms** [comment]
dann werde ich das überprüfen aller tische noch einbauen

**Comment by darenegade** [comment]
Oder du machst einen regelmäßigen Job draus, das ist vielleicht sogar noch besser
