### ISSUE TITLE
Fehlerhandling Phil

### ISSUE THREAD

**Issue by darenegade** [FabianHoltkoetter/VerteilteSystemePraktikum#14]
kein einziger try/catch um alles, sondern sauber um die einzelnen Befehle, die schief laufen können und entsprechend reagieren

**Comment by FabianWilms** [comment]
closed with https://github.com/FabianHoltkoetter/VerteilteSystemePraktikum/commit/87d8d976b2a67ccaf4ae99387697820d2c87dd19
