### ISSUE TITLE
Dining Philosopher 

### ISSUE THREAD

**Issue by darenegade** [FabianHoltkoetter/VerteilteSystemePraktikum#4]
Hier können wir ja noch Ideen zur Umsetzung usw. diskutieren.

@FabianHoltkoetter

**Comment by darenegade** [comment]
Wenn ein Philosoph eine Runde rumgegangen ist, dann geht er in den sleep und wenn ein andere mit dem essen fertig ist, dann weckt er diesen auf.

**Comment by darenegade** [comment]
Anzeige noch über Observer Pattern

**Comment by darenegade** [comment]
@FabianHoltkoetter Ich hab noch ein paar Optimierungen eingebaut und die Ausgabe geändert. 
Was sagst du dazu?

**Comment by FabianWilms** [comment]
Habs mal gezogen und mit 3 Philosophen und 2 Plätzen gestartet. Direkt kam das hier:
<img width="688" alt="crash" src="https://cloud.githubusercontent.com/assets/10800158/14366117/7aa071be-fd11-11e5-8f9e-500ef57cf3f0.PNG">

Ein ähnliches Problem hatte ich genau so auch, als wir noch manche aufrufe innerhalb der philosophen-klasse gemacht haben. Scheint wieder ein synchronisationsproblem zu sein

**Comment by FabianWilms** [comment]
Hat sich https://github.com/FabianHoltkoetter/VerteilteSystemePraktikum/commit/c2e58dec2e49382814a443e774264c96e0abe7ee

**Comment by darenegade** [comment]
Wenn du das dahinter schreibst, dann passt es? Komisch. 
Aber die Ausgabe sollte davor kommen, damit die Reihenfolge passt. Schau ich mir nochmal an. 

Gesendet von meinem Toaster

**Comment by darenegade** [comment]
Ach Fuck natürlich. Ich muss den Platz zwischen speichern.  Sonst übergibt man -1

**Comment by darenegade** [comment]
Sorry 😅

**Comment by FabianWilms** [comment]
Das kommt davon wenn du immer mit deinem Toaster entwickelst 😜

**Comment by darenegade** [comment]
Hey, nichts gegen meinen Toaster. Mit Vollkorn Toast hat er um einiges mehr Kerne als dein Rechner.

**Comment by FabianWilms** [comment]
![rekt](http://vignette2.wikia.nocookie.net/lalaloopsyland/images/b/b8/Rekt.jpg/revision/latest?cb=20150107020612)

**Comment by darenegade** [comment]
Aufgabe sollte fertig sein
